### ISSUE TITLE
ValueError while loading Cosmo_23.5 from `tensorflow_datasets`

### ISSUE THREAD

**Issue by jwuphysics** [EiffL/Quarks2CosmosDataChallenge#5]
In `notebooks/PartII-GenerativeModels.ipynb`, the first code cell under **Step I: Preparing training data** and the first code cell under **Bonus: Denoising Score Matching** should be 
```python
dset = tfds.load('Cosmos/Cosmos_23.5', split=tfds.Split.TRAIN)
```
but it should be
```python
dset = tfds.load('Cosmos/23.5', split=tfds.Split.TRAIN)
```

Otherwise we'll see the error:
```python
ValueError: Failed to construct dataset cosmos: BuilderConfig Cosmos_23.5 not found. Available: ['23.5', '25.2'] 
```

**Comment by EiffL** [comment]
It should be fixed now, thanks @jwuphysics for the issue!
